/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Empresa;
import org.openapitools.client.model.RegistroPracticas;
import org.openapitools.client.model.Tutor;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Alumno
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-14T16:54:04.731981300+01:00[Europe/Madrid]", comments = "Generator version: 7.11.0")
public class Alumno {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_NOMBRE_COMPLETO = "nombreCompleto";
  @SerializedName(SERIALIZED_NAME_NOMBRE_COMPLETO)
  @javax.annotation.Nonnull
  private String nombreCompleto;

  /**
   * Gets or Sets ciclo
   */
  @JsonAdapter(CicloEnum.Adapter.class)
  public enum CicloEnum {
    DAM("DAM"),
    
    DAW("DAW"),
    
    ASIR("ASIR");

    private String value;

    CicloEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CicloEnum fromValue(String value) {
      for (CicloEnum b : CicloEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CicloEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CicloEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CicloEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CicloEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CicloEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CICLO = "ciclo";
  @SerializedName(SERIALIZED_NAME_CICLO)
  @javax.annotation.Nullable
  private CicloEnum ciclo;

  /**
   * Gets or Sets evaluacion
   */
  @JsonAdapter(EvaluacionEnum.Adapter.class)
  public enum EvaluacionEnum {
    MARZO("Marzo"),
    
    SEPTIEMBRE("Septiembre");

    private String value;

    EvaluacionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EvaluacionEnum fromValue(String value) {
      for (EvaluacionEnum b : EvaluacionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<EvaluacionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EvaluacionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EvaluacionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return EvaluacionEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      EvaluacionEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_EVALUACION = "evaluacion";
  @SerializedName(SERIALIZED_NAME_EVALUACION)
  @javax.annotation.Nullable
  private EvaluacionEnum evaluacion;

  public static final String SERIALIZED_NAME_AñO = "año";
  @SerializedName(SERIALIZED_NAME_AñO)
  @javax.annotation.Nullable
  private Integer año;

  public static final String SERIALIZED_NAME_TUTOR = "tutor";
  @SerializedName(SERIALIZED_NAME_TUTOR)
  @javax.annotation.Nullable
  private Tutor tutor;

  public static final String SERIALIZED_NAME_EMPRESA = "empresa";
  @SerializedName(SERIALIZED_NAME_EMPRESA)
  @javax.annotation.Nullable
  private Empresa empresa;

  public static final String SERIALIZED_NAME_REGISTROS_PRACTICAS = "registrosPracticas";
  @SerializedName(SERIALIZED_NAME_REGISTROS_PRACTICAS)
  @javax.annotation.Nullable
  private List<RegistroPracticas> registrosPracticas = new ArrayList<>();

  public Alumno() {
  }

  public Alumno id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public Alumno nombreCompleto(@javax.annotation.Nonnull String nombreCompleto) {
    this.nombreCompleto = nombreCompleto;
    return this;
  }

  /**
   * Get nombreCompleto
   * @return nombreCompleto
   */
  @javax.annotation.Nonnull
  public String getNombreCompleto() {
    return nombreCompleto;
  }

  public void setNombreCompleto(@javax.annotation.Nonnull String nombreCompleto) {
    this.nombreCompleto = nombreCompleto;
  }


  public Alumno ciclo(@javax.annotation.Nullable CicloEnum ciclo) {
    this.ciclo = ciclo;
    return this;
  }

  /**
   * Get ciclo
   * @return ciclo
   */
  @javax.annotation.Nullable
  public CicloEnum getCiclo() {
    return ciclo;
  }

  public void setCiclo(@javax.annotation.Nullable CicloEnum ciclo) {
    this.ciclo = ciclo;
  }


  public Alumno evaluacion(@javax.annotation.Nullable EvaluacionEnum evaluacion) {
    this.evaluacion = evaluacion;
    return this;
  }

  /**
   * Get evaluacion
   * @return evaluacion
   */
  @javax.annotation.Nullable
  public EvaluacionEnum getEvaluacion() {
    return evaluacion;
  }

  public void setEvaluacion(@javax.annotation.Nullable EvaluacionEnum evaluacion) {
    this.evaluacion = evaluacion;
  }


  public Alumno año(@javax.annotation.Nullable Integer año) {
    this.año = año;
    return this;
  }

  /**
   * Get año
   * @return año
   */
  @javax.annotation.Nullable
  public Integer getAño() {
    return año;
  }

  public void setAño(@javax.annotation.Nullable Integer año) {
    this.año = año;
  }


  public Alumno tutor(@javax.annotation.Nullable Tutor tutor) {
    this.tutor = tutor;
    return this;
  }

  /**
   * Get tutor
   * @return tutor
   */
  @javax.annotation.Nullable
  public Tutor getTutor() {
    return tutor;
  }

  public void setTutor(@javax.annotation.Nullable Tutor tutor) {
    this.tutor = tutor;
  }


  public Alumno empresa(@javax.annotation.Nullable Empresa empresa) {
    this.empresa = empresa;
    return this;
  }

  /**
   * Get empresa
   * @return empresa
   */
  @javax.annotation.Nullable
  public Empresa getEmpresa() {
    return empresa;
  }

  public void setEmpresa(@javax.annotation.Nullable Empresa empresa) {
    this.empresa = empresa;
  }


  public Alumno registrosPracticas(@javax.annotation.Nullable List<RegistroPracticas> registrosPracticas) {
    this.registrosPracticas = registrosPracticas;
    return this;
  }

  public Alumno addRegistrosPracticasItem(RegistroPracticas registrosPracticasItem) {
    if (this.registrosPracticas == null) {
      this.registrosPracticas = new ArrayList<>();
    }
    this.registrosPracticas.add(registrosPracticasItem);
    return this;
  }

  /**
   * Get registrosPracticas
   * @return registrosPracticas
   */
  @javax.annotation.Nullable
  public List<RegistroPracticas> getRegistrosPracticas() {
    return registrosPracticas;
  }

  public void setRegistrosPracticas(@javax.annotation.Nullable List<RegistroPracticas> registrosPracticas) {
    this.registrosPracticas = registrosPracticas;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Alumno alumno = (Alumno) o;
    return Objects.equals(this.id, alumno.id) &&
        Objects.equals(this.nombreCompleto, alumno.nombreCompleto) &&
        Objects.equals(this.ciclo, alumno.ciclo) &&
        Objects.equals(this.evaluacion, alumno.evaluacion) &&
        Objects.equals(this.año, alumno.año) &&
        Objects.equals(this.tutor, alumno.tutor) &&
        Objects.equals(this.empresa, alumno.empresa) &&
        Objects.equals(this.registrosPracticas, alumno.registrosPracticas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nombreCompleto, ciclo, evaluacion, año, tutor, empresa, registrosPracticas);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Alumno {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nombreCompleto: ").append(toIndentedString(nombreCompleto)).append("\n");
    sb.append("    ciclo: ").append(toIndentedString(ciclo)).append("\n");
    sb.append("    evaluacion: ").append(toIndentedString(evaluacion)).append("\n");
    sb.append("    año: ").append(toIndentedString(año)).append("\n");
    sb.append("    tutor: ").append(toIndentedString(tutor)).append("\n");
    sb.append("    empresa: ").append(toIndentedString(empresa)).append("\n");
    sb.append("    registrosPracticas: ").append(toIndentedString(registrosPracticas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("nombreCompleto");
    openapiFields.add("ciclo");
    openapiFields.add("evaluacion");
    openapiFields.add("año");
    openapiFields.add("tutor");
    openapiFields.add("empresa");
    openapiFields.add("registrosPracticas");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("nombreCompleto");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Alumno
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Alumno.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Alumno is not found in the empty JSON string", Alumno.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Alumno.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Alumno` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Alumno.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("nombreCompleto").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nombreCompleto` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nombreCompleto").toString()));
      }
      if ((jsonObj.get("ciclo") != null && !jsonObj.get("ciclo").isJsonNull()) && !jsonObj.get("ciclo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ciclo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ciclo").toString()));
      }
      // validate the optional field `ciclo`
      if (jsonObj.get("ciclo") != null && !jsonObj.get("ciclo").isJsonNull()) {
        CicloEnum.validateJsonElement(jsonObj.get("ciclo"));
      }
      if ((jsonObj.get("evaluacion") != null && !jsonObj.get("evaluacion").isJsonNull()) && !jsonObj.get("evaluacion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `evaluacion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("evaluacion").toString()));
      }
      // validate the optional field `evaluacion`
      if (jsonObj.get("evaluacion") != null && !jsonObj.get("evaluacion").isJsonNull()) {
        EvaluacionEnum.validateJsonElement(jsonObj.get("evaluacion"));
      }
      // validate the optional field `tutor`
      if (jsonObj.get("tutor") != null && !jsonObj.get("tutor").isJsonNull()) {
        Tutor.validateJsonElement(jsonObj.get("tutor"));
      }
      // validate the optional field `empresa`
      if (jsonObj.get("empresa") != null && !jsonObj.get("empresa").isJsonNull()) {
        Empresa.validateJsonElement(jsonObj.get("empresa"));
      }
      if (jsonObj.get("registrosPracticas") != null && !jsonObj.get("registrosPracticas").isJsonNull()) {
        JsonArray jsonArrayregistrosPracticas = jsonObj.getAsJsonArray("registrosPracticas");
        if (jsonArrayregistrosPracticas != null) {
          // ensure the json data is an array
          if (!jsonObj.get("registrosPracticas").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `registrosPracticas` to be an array in the JSON string but got `%s`", jsonObj.get("registrosPracticas").toString()));
          }

          // validate the optional field `registrosPracticas` (array)
          for (int i = 0; i < jsonArrayregistrosPracticas.size(); i++) {
            RegistroPracticas.validateJsonElement(jsonArrayregistrosPracticas.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Alumno.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Alumno' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Alumno> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Alumno.class));

       return (TypeAdapter<T>) new TypeAdapter<Alumno>() {
           @Override
           public void write(JsonWriter out, Alumno value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Alumno read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Alumno given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Alumno
   * @throws IOException if the JSON string is invalid with respect to Alumno
   */
  public static Alumno fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Alumno.class);
  }

  /**
   * Convert an instance of Alumno to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

