/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Fecha;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * RegistroPracticas
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-14T16:54:04.731981300+01:00[Europe/Madrid]", comments = "Generator version: 7.11.0")
public class RegistroPracticas {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_FECHA = "fecha";
  @SerializedName(SERIALIZED_NAME_FECHA)
  @javax.annotation.Nullable
  private Fecha fecha;

  public static final String SERIALIZED_NAME_CANTIDAD_HORAS = "cantidadHoras";
  @SerializedName(SERIALIZED_NAME_CANTIDAD_HORAS)
  @javax.annotation.Nullable
  private Double cantidadHoras;

  public static final String SERIALIZED_NAME_DESCRIPCION = "descripcion";
  @SerializedName(SERIALIZED_NAME_DESCRIPCION)
  @javax.annotation.Nonnull
  private String descripcion;

  public RegistroPracticas() {
  }

  public RegistroPracticas id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public RegistroPracticas fecha(@javax.annotation.Nullable Fecha fecha) {
    this.fecha = fecha;
    return this;
  }

  /**
   * Get fecha
   * @return fecha
   */
  @javax.annotation.Nullable
  public Fecha getFecha() {
    return fecha;
  }

  public void setFecha(@javax.annotation.Nullable Fecha fecha) {
    this.fecha = fecha;
  }


  public RegistroPracticas cantidadHoras(@javax.annotation.Nullable Double cantidadHoras) {
    this.cantidadHoras = cantidadHoras;
    return this;
  }

  /**
   * Get cantidadHoras
   * minimum: 0
   * maximum: 8
   * @return cantidadHoras
   */
  @javax.annotation.Nullable
  public Double getCantidadHoras() {
    return cantidadHoras;
  }

  public void setCantidadHoras(@javax.annotation.Nullable Double cantidadHoras) {
    this.cantidadHoras = cantidadHoras;
  }


  public RegistroPracticas descripcion(@javax.annotation.Nonnull String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

  /**
   * Get descripcion
   * @return descripcion
   */
  @javax.annotation.Nonnull
  public String getDescripcion() {
    return descripcion;
  }

  public void setDescripcion(@javax.annotation.Nonnull String descripcion) {
    this.descripcion = descripcion;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegistroPracticas registroPracticas = (RegistroPracticas) o;
    return Objects.equals(this.id, registroPracticas.id) &&
        Objects.equals(this.fecha, registroPracticas.fecha) &&
        Objects.equals(this.cantidadHoras, registroPracticas.cantidadHoras) &&
        Objects.equals(this.descripcion, registroPracticas.descripcion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, fecha, cantidadHoras, descripcion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegistroPracticas {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    fecha: ").append(toIndentedString(fecha)).append("\n");
    sb.append("    cantidadHoras: ").append(toIndentedString(cantidadHoras)).append("\n");
    sb.append("    descripcion: ").append(toIndentedString(descripcion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("fecha");
    openapiFields.add("cantidadHoras");
    openapiFields.add("descripcion");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("descripcion");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RegistroPracticas
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RegistroPracticas.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RegistroPracticas is not found in the empty JSON string", RegistroPracticas.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RegistroPracticas.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RegistroPracticas` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RegistroPracticas.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `fecha`
      if (jsonObj.get("fecha") != null && !jsonObj.get("fecha").isJsonNull()) {
        Fecha.validateJsonElement(jsonObj.get("fecha"));
      }
      if (!jsonObj.get("descripcion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `descripcion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("descripcion").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RegistroPracticas.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RegistroPracticas' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RegistroPracticas> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RegistroPracticas.class));

       return (TypeAdapter<T>) new TypeAdapter<RegistroPracticas>() {
           @Override
           public void write(JsonWriter out, RegistroPracticas value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RegistroPracticas read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RegistroPracticas given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RegistroPracticas
   * @throws IOException if the JSON string is invalid with respect to RegistroPracticas
   */
  public static RegistroPracticas fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RegistroPracticas.class);
  }

  /**
   * Convert an instance of RegistroPracticas to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

