/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ChangePasswordRequest
 */
public class ChangePasswordRequestTest {
    private final ChangePasswordRequest model = new ChangePasswordRequest();

    /**
     * Model tests for ChangePasswordRequest
     */
    @Test
    public void testChangePasswordRequest() {
        // TODO: test ChangePasswordRequest
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'oldPassword'
     */
    @Test
    public void oldPasswordTest() {
        // TODO: test oldPassword
    }

    /**
     * Test the property 'newPassword'
     */
    @Test
    public void newPasswordTest() {
        // TODO: test newPassword
    }

}
