/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for Empresa
 */
public class EmpresaTest {
    private final Empresa model = new Empresa();

    /**
     * Model tests for Empresa
     */
    @Test
    public void testEmpresa() {
        // TODO: test Empresa
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'nombreEmpresa'
     */
    @Test
    public void nombreEmpresaTest() {
        // TODO: test nombreEmpresa
    }

    /**
     * Test the property 'activo'
     */
    @Test
    public void activoTest() {
        // TODO: test activo
    }

}
