/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for Fecha
 */
public class FechaTest {
    private final Fecha model = new Fecha();

    /**
     * Model tests for Fecha
     */
    @Test
    public void testFecha() {
        // TODO: test Fecha
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'fecha'
     */
    @Test
    public void fechaTest() {
        // TODO: test fecha
    }

    /**
     * Test the property 'año'
     */
    @Test
    public void añoTest() {
        // TODO: test año
    }

    /**
     * Test the property 'evaluacion'
     */
    @Test
    public void evaluacionTest() {
        // TODO: test evaluacion
    }

}
