/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for RegistroPracticas
 */
public class RegistroPracticasTest {
    private final RegistroPracticas model = new RegistroPracticas();

    /**
     * Model tests for RegistroPracticas
     */
    @Test
    public void testRegistroPracticas() {
        // TODO: test RegistroPracticas
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'fecha'
     */
    @Test
    public void fechaTest() {
        // TODO: test fecha
    }

    /**
     * Test the property 'cantidadHoras'
     */
    @Test
    public void cantidadHorasTest() {
        // TODO: test cantidadHoras
    }

    /**
     * Test the property 'descripcion'
     */
    @Test
    public void descripcionTest() {
        // TODO: test descripcion
    }

}
