/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for Tutor
 */
public class TutorTest {
    private final Tutor model = new Tutor();

    /**
     * Model tests for Tutor
     */
    @Test
    public void testTutor() {
        // TODO: test Tutor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'nombreCompleto'
     */
    @Test
    public void nombreCompletoTest() {
        // TODO: test nombreCompleto
    }

    /**
     * Test the property 'activo'
     */
    @Test
    public void activoTest() {
        // TODO: test activo
    }

}
