/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for Usuario
 */
public class UsuarioTest {
    private final Usuario model = new Usuario();

    /**
     * Model tests for Usuario
     */
    @Test
    public void testUsuario() {
        // TODO: test Usuario
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'nombreUsuario'
     */
    @Test
    public void nombreUsuarioTest() {
        // TODO: test nombreUsuario
    }

    /**
     * Test the property 'contraseña'
     */
    @Test
    public void contraseñaTest() {
        // TODO: test contraseña
    }

    /**
     * Test the property 'alumno'
     */
    @Test
    public void alumnoTest() {
        // TODO: test alumno
    }

    /**
     * Test the property 'tutor'
     */
    @Test
    public void tutorTest() {
        // TODO: test tutor
    }

    /**
     * Test the property 'activo'
     */
    @Test
    public void activoTest() {
        // TODO: test activo
    }

}
