/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Alumno;
import org.openapitools.client.model.ChangePasswordRequest;
import org.openapitools.client.model.RegistroPracticas;
import org.openapitools.client.model.Usuario;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FctApiServiceApi
 */
@Disabled
public class FctApiServiceApiTest {

    private final FctApiServiceApi api = new FctApiServiceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addRegistroPracticasTest() throws ApiException {
        Integer idUser = null;
        RegistroPracticas registroPracticas = null;
        api.addRegistroPracticas(idUser, registroPracticas);
        // TODO: test validations
    }

    /**
     * Cambio de contraseña
     *
     * Método que devuelve un request cambiando la contraseña del usuario que lo solicite
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void changePasswordTest() throws ApiException {
        ChangePasswordRequest changePasswordRequest = null;
        Usuario response = api.changePassword(changePasswordRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDatosAlumnoTest() throws ApiException {
        Integer idUser = null;
        Alumno response = api.getDatosAlumno(idUser);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDetailTest() throws ApiException {
        Integer idUser = null;
        List<RegistroPracticas> response = api.getDetail(idUser);
        // TODO: test validations
    }

    /**
     * Login de usuario
     *
     * Método que devuelve un usuario que coincida con el username y la contraseña pasadas por parámetros
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void loginTest() throws ApiException {
        String username = null;
        String password = null;
        Usuario response = api.login(username, password);
        // TODO: test validations
    }

}
